#!/usr/bin/env ruby

require "thor"
require "date"
require "time"

class String
  def kebab_case
    gsub(/([A-Z]+)([A-Z][a-z])/,'\1-\2').
    gsub(/([a-z\d])([A-Z])/,'\1-\2').
    tr('_', '-').
    gsub(/\s/, '-').
    gsub(/--+/, '-').
    downcase
  end
end

class TIL < Thor
  desc "new", "Create new TIL entry"
  def new
    puts "Creating new entry"
    entry_name = ask "Entry name:"
    entry_date = ask "Date:", default: Time.now.strftime("%Y-%m-%d")

    entry_date = Date.parse(entry_date).strftime("%Y-%m-%d")

    file_name = "#{entry_date}-#{entry_name.kebab_case}.md"
    puts file_name
  end
end

TIL.start(ARGV)
