#!/usr/bin/env ruby

require "thor"
require "date"
require "fileutils"
require "time"

class String
  def kebab_case
    gsub(/([A-Z]+)([A-Z][a-z])/,'\1-\2').
    gsub(/([a-z\d])([A-Z])/,'\1-\2').
    tr('_', '-').
    gsub(/\s/, '-').
    gsub(/--+/, '-').
    downcase
  end
end

def contents(name, date, tags)
  <<~EOF
    ---
    name: #{name}
    date: #{date}
    tags: #{tags}
    ---
  EOF
end

class TIL < Thor
  desc "new", "Create new TIL entry"
  def new
    entry_name = nil

    loop do
      entry_name = ask "Entry name:"
      break unless entry_name.empty?
      puts "Entry name required"
    end

    entry_date = ask "Date:", default: Time.now.strftime("%Y-%m-%d")
    entry_date = Date.parse(entry_date).strftime("%Y-%m-%d")
    file_name = "#{entry_date}-#{entry_name.kebab_case}.md"

    entry_tags = ask("Tags (Comma separated):")
      .split(",")
      .map(&:strip)
      .reject(&:nil?)
      .reject(&:empty?)
      .join(", ")

    FileUtils.mkdir_p("entries")
    File.write("entries/#{file_name}", contents(entry_name, entry_date, entry_tags))

    system("$EDITOR entries/#{file_name}")
  end
end

TIL.start(ARGV)
